grid-rows: 3
grid-gap: 10
chartTitle: ''{
	grid-rows: 2
	grid-columns: 1
	grid-gap: 0
	width: 400
	Title: "Title\n1,0.1"{
		width: 400
	}
	Subtitle: "Subtitle\n1,0.1"
}
main: ''{
	grid-columns: 3
	grid-gap: 0
	axisLeft: "axisLeft\n0.1,0.7"{
		width: 80
	}
	Chart: "Chart\n0.8,0.7"{
		width: 240
	}
	axisRight: "axisRight\n0.1,0.7"{
		width: 80
	}
}
Legend: "Legend\n1,0.1"{
	width: 400
}
